<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>proteomiqon-ratiolfq</ToolCommandName>
    <RootNamespace>RatioLFQ</RootNamespace>
    <AssemblyName>ProteomIQon.RatioLFQ</AssemblyName>
    <Name>ProteomIQon.RatioLFQ</Name>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <Authors>David Zimmer, Caroline Ott, Kevin Schneider, Timo Muehlhaus</Authors>
    <Description>ProteomIQon.RatioLFQ - computational proteomics</Description>
    <Summary>ProteomIQon.RatioLFQ - computational proteomics</Summary>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://csbiology.github.io/ProteomIQon/</PackageProjectUrl>
    <!--<PackageIconUrl>https://github.com/CSBiology/ProteomIQon</PackageIconUrl>-->
    <PackageTags>fsharp dotnet proteomics</PackageTags>
    <RepositoryUrl>https://github.com/CSBiology/ProteomIQon</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <FsDocsLicenseLink>https://github.com/CSBiology/ProteomIQon/blob/master/LICENSE</FsDocsLicenseLink>
    <FsDocsReleaseNotesLink>https://github.com/CSBiology/ProteomIQon/blob/master/RELEASE_NOTES.md</FsDocsReleaseNotesLink>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="RatioLFQ.fs" />
    <Compile Include="CLIArgumentParsing.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup />
  <ItemGroup>
    <ProjectReference Include="..\ProteomIQon\ProteomIQon.fsproj"></ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Argu" Version="[6.1.1]" />
    <PackageReference Include="NLog" Version="[4.7.8]" />
    <PackageReference Include="FSharp.Stats" Version="[0.4.0]" />
  </ItemGroup>
</Project>
